### ISSUE TITLE
SlimGems?

### ISSUE THREAD

**Issue by felixrabe** [scoop/bundle_outdated#4]
I've got

```
$ gem -v
SlimGems 1.3.9.4
```

Using bundle_outdated in our project raises on `bundle install`:

```
Gem::InstallError: bundle_outdated requires SlimGems version >= 1.6.0. Try 'gem update --system' to update SlimGems itself.
```

Is this a known fact? Do you know of any workaround?

**Comment by scoop** [comment]
Using `bundle_outdated` with SlimGems isn't supported at this point. Since I'm not using SlimGems myself, I won't add support for it, but I'll merge a patch if you come up with one.
