### ISSUE TITLE
I get an error

### ISSUE THREAD

**Issue by Zeneixe** [scoop/bundle_outdated#5]
/home/vagrant/lib/ruby/2.0.0/rubygems/version.rb:191:in `initialize': Malformed version number string ~> 3.2.3 (ArgumentError)

**Comment by Zeneixe** [comment]
I have a fix for this

**Comment by Zeneixe** [comment]
our Gemfile had something like:
gem 'sass-rails', "  ~> 3.2.3"

The regexp doesn't like prefix spaces, I am sending a pull request with a test+fix

**Comment by Fuffi** [comment]
Has this been merged?
